Feature/exportar cardapio
partithura-estagiarios/frontend-intranet-elyte pull request #25
Opened 2023-04-20 16:26 UTC by jorgebinho

2023-04-20 17:00 UTC, gabriel-gras commented on src/components/MenuImage.vue
> +    no-transition
classes sem efeito

2023-04-20 17:41 UTC, gabriel-gras commented on src/components/MenuImage.vue
> +const dates: Ref<Array<Date>> = ref([]);
melhorar as declarações, muito confuso

2023-04-28 16:36 UTC, julianostroschon requested changes
tem alguns comentários no projeto

2023-04-28 16:36 UTC, julianostroschon commented on src/components/MenuImage.vue
> +menus.forEach((element) => {
um tanto confusa essa solução

2023-04-28 16:36 UTC, julianostroschon commented on src/components/MenuImage.vue
> +  datas.value.push(element.getTime());
mais uma iteração sobre um array que foi criado logo acima

2023-04-28 16:36 UTC, julianostroschon commented on src/components/buttons/PrintButton.vue
> +  window.print();
essa função pode ser acionada no momento do evento direto, não precisa de uma função para acionar a função

2023-04-28 16:36 UTC, julianostroschon commented on src/helpers/date.ts
> +  return date;
return direto da criação, não atribuir para retornar

2023-04-28 16:36 UTC, julianostroschon commented on src/helpers/date.ts
> +  return date;
o mesmo do comentário acima

2023-04-28 16:36 UTC, julianostroschon commented on src/views/home/Index.vue
> +  <HeaderBar class="q-mb-xl" />
se teve de definir o mesmo comportamento em todos os lugares que esse componente é chamado, esse comportamento deve estar no componente

2023-07-03 13:24 UTC, closed without merging