Cadastro de usuários
partithura-estagiarios/frontend-intranet-elyte pull request #40
Opened 2023-08-14 12:50 UTC by Sckyz

![image](https://github.com/partithura-estagiarios/frontend-intranet-elyte/assets/122920355/aeb75513-73ed-4fe6-8229-45fb04da474d)

2023-08-14 12:54 UTC, julianostroschon commented on locales/en/titles.ts
> +    register: "Cadastrar Usuário",
creio que deveria estar em inglês aqui

2023-08-14 12:54 UTC, julianostroschon commented on src/components/Login/RegisterUser.vue
> +const emailPattern = /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/;
fazer a validação conforme a vee-validate

2023-08-14 12:55 UTC, julianostroschon requested changes
uns comentários aí

2023-08-14 12:58 UTC, Sckyz commented on locales/en/titles.ts
> +    register: "Cadastrar Usuário",
tradução para a língua inglesa

2023-08-16 13:31 UTC, Sckyz commented on src/components/Login/RegisterUser.vue
> +const emailPattern = /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/;
prontinho

2023-08-16 16:34 UTC, julianostroschon submitted a review, later dismissed

2023-08-17 14:36 UTC, lauragabriele submitted a review, later dismissed

2023-08-17 14:36 UTC, lauragabriele commented on src/components/Login/RegisterUser.vue
> +import { Field, Form } from "vee-validate";
esse projeto tem auto import, ou seja, não é necessário importar.

2023-08-18 11:11 UTC, lauragabriele approved these changes, later dismissed

2023-08-23 12:34 UTC, julianostroschon commented on src/components/Login/RegisterUser.vue
> +  console.log(data);
console.log não deve ir para o servidor

2023-08-23 12:42 UTC, Sckyz commented on src/components/Login/RegisterUser.vue
> +  console.log(data);
chopp?

2023-08-23 13:02 UTC, Sckyz commented on src/components/Login/RegisterUser.vue
> +  console.log(data);
removido

2023-08-25 16:07 UTC, julianostroschon approved these changes, later dismissed

2023-08-25 16:48 UTC, lauragabriele submitted a review, later dismissed

2023-09-21 14:06 UTC, julianostroschon approved these changes

2023-09-21 14:07 UTC, lauragabriele approved these changes

2023-09-21 14:07 UTC, merged