Recuperação de senha
partithura-estagiarios/frontend-intranet-elyte pull request #41
Opened 2023-08-16 13:45 UTC by Sckyz

2023-08-16 16:35 UTC, julianostroschon commented on locales/br/notifications.ts
> +    invalidEmail: "Não é um email válido",
email inválido

2023-08-16 16:35 UTC, julianostroschon commented on locales/br/notifications.ts
> +    emptyField: "Algum campo está vazio | O campo está vazio",
uso de plural pra isso?

2023-08-16 16:37 UTC, julianostroschon commented on src/components/DynamicDialog/SystemModals/AddSystemDialog.vue
> +  sistema: props.item[0].sistema,
pq a posição 0?

2023-08-16 16:37 UTC, julianostroschon commented on src/components/DynamicDialog/SystemModals/AddSystemDialog.vue
> +    emits("reload");
emissão de 2 eventos, desnecessário

2023-08-16 16:37 UTC, julianostroschon commented on src/components/DynamicDialog/SystemModals/AddSystemDialog.vue
> +      >
validação co,m a vee-validate

2023-08-16 16:38 UTC, julianostroschon commented on src/components/DynamicDialog/SystemModals/EditSystemDialog.vue
> +    emits("reload");
emissão de 2 eventos, desnecesário

2023-08-16 16:38 UTC, julianostroschon commented on src/components/DynamicDialog/SystemModals/EditSystemDialog.vue
> +      >
validação

2023-08-16 16:38 UTC, julianostroschon commented on src/components/Login/ChangePassword.vue
> +  }
validação

2023-08-16 19:53 UTC, julianostroschon commented on src/components/SistemaGestao/SistemaGestao.vue
> +  { label: "Adicionar", icon: "add", component: AddSystemDialog },
tradução

2023-08-16 19:54 UTC, julianostroschon commented on src/components/SistemaRh/SistemaRh.vue
> +  { label: "Adicionar", icon: "add", component: AddSystemDialog },
tradução

2023-08-16 19:55 UTC, julianostroschon requested changes
uns comentários

2023-08-21 16:43 UTC, Sckyz commented on locales/br/notifications.ts
> +    invalidEmail: "Não é um email válido",
Troquei "Não é um email válido" para "Email inválido"

2023-08-21 16:43 UTC, Sckyz commented on locales/br/notifications.ts
> +    emptyField: "Algum campo está vazio | O campo está vazio",
Uso incorreto de pluralização, agora está arrrumado

2023-08-21 16:49 UTC, Sckyz commented on src/components/DynamicDialog/SystemModals/AddSystemDialog.vue
> +    emits("reload");
ja foi resolvido pelo vitor

2023-08-21 16:50 UTC, Sckyz commented on src/components/DynamicDialog/SystemModals/AddSystemDialog.vue
> +  sistema: props.item[0].sistema,
pergunta pro vitor

2023-08-21 16:57 UTC, Sckyz commented on src/components/SistemaRh/SistemaRh.vue
> +  { label: "Adicionar", icon: "add", component: AddSystemDialog },
feita tradução destes botões

2023-08-21 16:59 UTC, Sckyz commented on src/components/DynamicDialog/SystemModals/EditSystemDialog.vue
> +    emits("reload");
eu nao consigo editar esse arquivo, diz que é só de leitura

2023-08-21 17:00 UTC, Sckyz commented on src/components/Login/ChangePassword.vue
> +  }
feita validação com vee-validate

2023-08-21 17:00 UTC, Sckyz commented on src/components/SistemaGestao/SistemaGestao.vue
> +  { label: "Adicionar", icon: "add", component: AddSystemDialog },
tradção feita

2023-08-21 17:00 UTC, Sckyz commented on src/components/DynamicDialog/SystemModals/AddSystemDialog.vue
> +      >
feito

2023-08-21 17:01 UTC, Sckyz commented on src/components/DynamicDialog/SystemModals/EditSystemDialog.vue
> +      >
eu nao consigo editar esse arquivo, diz que é só de leitura

2023-08-21 17:02 UTC, Sckyz commented on src/components/DynamicDialog/SystemModals/AddSystemDialog.vue
> +  sistema: props.item[0].sistema,
eu nao consigo editar esse arquivo, diz que é só de leitura

2023-08-21 17:31 UTC, Sckyz commented
![image](https://github.com/partithura-estagiarios/frontend-intranet-elyte/assets/122920355/cd8e9f3e-5786-452d-88b5-14f8aba18acc)


eu cortei sem terminar de escrever hahah,.... espaços em branco

2023-08-22 17:59 UTC, Sckyz commented on src/components/DynamicDialog/SystemModals/EditSystemDialog.vue
> +      >
pronto, feita a validação com vee-validate + yup

2023-08-23 11:20 UTC, Sckyz commented on src/components/DynamicDialog/SystemModals/AddSystemDialog.vue
> +  sistema: props.item[0].sistema,
Pois estava pegando o primeiro index do array para deixar como default, se voce fosse criar um sistema em gestão, "gestão" ja estária no input do modal, mesmo serve para sistema rh. Porém agora ja arrumei e esta de outra forma

2023-08-23 11:26 UTC, Sckyz commented on src/components/DynamicDialog/SystemModals/AddSystemDialog.vue
> +      >
feito

2023-08-23 12:40 UTC, julianostroschon commented on src/components/SistemaGestao/SistemaGestao.vue
> +            system="gestão"
pq esse texto aqui?

2023-08-23 12:40 UTC, julianostroschon commented on src/graphql/changePwd/ChangePwd.gql
> +mutation UpdatePassword($data: changePasswordInput!) {
tipos devem começar com letra maiúscula

2023-08-23 13:01 UTC, Sckyz commented on src/graphql/changePwd/ChangePwd.gql
> +mutation UpdatePassword($data: changePasswordInput!) {
pronto, mudei para ChangePasswordInput

2023-08-25 16:07 UTC, julianostroschon approved these changes

2023-08-29 13:27 UTC, vitorcorreasx approved these changes

2023-08-29 13:32 UTC, merged