Feature/menu creation
partithura-estagiarios/frontend-intranet-elyte pull request #42
Opened 2023-08-16 16:49 UTC by lauragabriele

tela de criação do menu
![image](https://github.com/partithura-estagiarios/frontend-intranet-elyte/assets/121674081/c9ea76bc-ff2e-4857-8618-d3e1ee832376)

tela de exibir o menu
![image](https://github.com/partithura-estagiarios/frontend-intranet-elyte/assets/121674081/6840df07-ba0a-4539-b50a-2ed9f7bcde64)

impressao do menu

![Uploading image.png…]()

2023-08-16 19:57 UTC, julianostroschon commented on src/components/CreateMenu/index.vue
> +  "Sábado",
tradução

2023-08-16 19:58 UTC, julianostroschon commented on src/components/DynamicDialog/SystemModals/AddSystemDialog.vue
>      emits("reload");
2 eventos seguidos pq?

2023-08-16 19:59 UTC, julianostroschon commented on src/components/Login/ChangePassword.vue
> +</script>
validação pela `vee-validate``

2023-08-16 20:01 UTC, julianostroschon commented on src/components/buttons/PrintButton.vue
> +</style>
sem `scoped`?

2023-08-16 20:01 UTC, julianostroschon commented on src/components/TabHeader.vue
> +      <q-route-tab :label="$t('home')" href="/home" />
e se usar a diretiva "to"?

2023-08-16 20:02 UTC, julianostroschon commented on src/entities/Menu.ts
> +  updated_at: string;
snake_case?

2023-08-16 20:02 UTC, julianostroschon commented on src/graphql/menu/CreateMenu.gql
> +    updated_at
deve ser camelCase

2023-08-17 16:22 UTC, jorgebinho commented on locales/en/notifications.ts
> +  successLogin: "You have been successfully logged in",
Esse arquivo ficou com um objeto no padrão que possui mensagens de sucesso e de falha e um objeto fail com apenas 3 mensagens de falha

2023-08-17 16:28 UTC, jorgebinho commented on src/components/CreateMenu/index.vue
> +});
```suggestion
const schema = yup.object({
    salad: makeRuleOfString(),
    repetir o processo aos demais campos
})

function makeRuleOfString(message: string = "warning.requiredField") {
   return yup.string().required().label(t(message))
}

```

2023-08-17 16:33 UTC, jorgebinho commented on src/components/Login/EnterEmail.vue
> +const form = reactive({
Não poderia ser apenas uma ref `emailRecover`?

2023-08-17 16:34 UTC, jorgebinho commented on src/components/SistemaRh/SistemaRh.vue
> +import DelSystemDialog from "../DynamicDialog/SystemModals/DelSystemDialog.vue";
Auto import não tankou?

2023-08-17 16:35 UTC, jorgebinho commented on src/components/SistemaRh/SistemaRh.vue
> +  { label: "Adicionar", icon: "add", component: AddSystemDialog },
Label sem tradução

2023-08-23 12:42 UTC, julianostroschon commented on src/components/CreateMenu/index.vue
> +  salad: makeRuleOfString(),
qual é a mensagem de erro caso a validação quebre?

2023-08-23 12:43 UTC, julianostroschon commented on src/views/menu/create.vue
> +  <createMenu />
os componentes devem estar PascalCase ou kebab-case

2023-08-29 13:38 UTC, julianostroschon approved these changes, later dismissed

2023-08-29 13:46 UTC, jorgebinho approved these changes, later dismissed

2023-09-05 17:42 UTC, jorgebinho commented on src/components/CreateMenu/index.vue
> +    console.error(err);
Console.log

2023-09-05 17:43 UTC, jorgebinho commented on src/components/CreateMenu/index.vue
> +          </q-date>
2 inputs diferentes apontando para o mesmo v-model pq?

2023-09-05 17:44 UTC, jorgebinho commented on src/components/CreateMenu/index.vue
> +          </span>
Todos os itens serão obrigatórios? E se a empresa não quiser colocar sopa em um dia por exemplo...

2023-09-05 17:46 UTC, jorgebinho commented on src/components/MenuTable/index.vue
> +    const date = menu.date.toISOString().split("T")[0];
O que seria esse "T"?

2023-09-05 17:51 UTC, jorgebinho commented on src/graphql/menu/AddMenu.gql
> +    id
Irá utilizar o id para algo? Se não poderia retornar um boolean apenas com a mensagem de sucesso ou não da execução da mutation

2023-09-05 17:52 UTC, jorgebinho commented on src/graphql/menu/EditMenu.gql
> +  }
O mesmo do comentário anterior serve aqui, pode retornar apenas boolean de execução caso não vá utilizar os dados...

2023-09-26 17:16 UTC, jorgebinho requested changes

2023-09-26 17:16 UTC, jorgebinho commented on src/components/CreateMenu/index.vue
> +    negativeNotify(t("notifications.fail.createMenu"));
Mensagem de erro no try e a mesma mensagem no catch 2 linhas abaixo

2023-09-26 17:16 UTC, jorgebinho commented on src/components/CreateMenu/index.vue
> +              </q-date>
Auto-close da tag q-date

2023-09-26 17:16 UTC, jorgebinho commented on src/components/MenuTable/index.vue
> +    const date = menu.date.toISOString().split("T")[0];
Remover "T" sem significado para evitar utilização de Magic Strings

2023-09-26 17:16 UTC, jorgebinho commented on src/entities/Menu.ts
Essa alteração não afetou a página de home?

2023-09-26 17:16 UTC, jorgebinho commented on src/graphql/menu/AddMenu.gql
> +    id
Se não utilizar o id para algo pode retornar o boolean da operação no lugar de um id

2023-09-26 17:16 UTC, jorgebinho commented on src/graphql/menu/EditMenu.gql
> +    dessert
O mesmo do comentário anterior pode ser utilizado aqui

2023-09-26 17:16 UTC, jorgebinho commented on src/views/menu/create.vue
> +// })
Comentário no repositório

2023-09-27 17:42 UTC, julianostroschon commented on locales/br/notifications.ts
> +    editMenu: "There was an error editing the menu",
inglês?

2023-09-27 17:43 UTC, julianostroschon commented on src/components/CreateMenu/index.vue
> +    label: "Salada",
tradução

2023-09-27 17:44 UTC, julianostroschon commented on src/components/CreateMenu/index.vue
> +                @click="showCalendar = false"
inline

2023-09-27 17:46 UTC, julianostroschon commented on src/components/MenuTable/index.vue
> +                  </div>
não creio que seja uma boa abordagem

2023-09-27 17:49 UTC, julianostroschon approved these changes

2023-09-27 17:51 UTC, jorgebinho approved these changes

2023-09-27 17:52 UTC, merged