Preview system
partithura-estagiarios/frontend-intranet-elyte pull request #65
Opened 2023-11-03 11:50 UTC by oGalhardo

Adição do IconSystem para o usuário ter uma lista de icons

2023-11-14 12:59 UTC, Sckyz requested changes

2023-11-14 12:59 UTC, Sckyz commented on locales/br/email.ts
> +    anonymousContact: " Contato Anônimo",
esse espaço antes de Contato é preciso?

2023-11-14 12:59 UTC, Sckyz commented on locales/br/text.ts
> +  icon: "Icone",
Ícone

2023-11-14 12:59 UTC, Sckyz commented on locales/br/titles.ts
> +    IconPreview: "Previsualização do Icone",
Pré-visualização

2023-11-14 12:59 UTC, Sckyz commented on src/components/ContactDirector/ContactDirector.vue
> +          label="Seu Nome Completo*"
tradução

2023-11-14 12:59 UTC, Sckyz commented on src/components/ContactDirector/ContactDirector.vue
> +          label="Seu Email*"
tradução

2023-11-14 12:59 UTC, Sckyz commented on src/components/ContactDirector/ContactDirector.vue
> +          label="Sua Matrícula *"
tradução

2023-11-14 12:59 UTC, Sckyz commented on src/components/ContactDirector/ContactDirector.vue
> +          label="Seu Contato *"
tradução

2023-11-14 12:59 UTC, Sckyz commented on src/components/ContactDirector/ContactDirector.vue
> +        <q-btn label="Enviar" type="submit" color="primary" />
tradução

2023-11-23 13:47 UTC, guigrasel approved these changes

2023-11-23 13:47 UTC, whoistaiza approved these changes

2023-11-23 13:49 UTC, Sckyz approved these changes

2023-11-23 13:49 UTC, merged