🐛 Correçoes em ramais, kcl [[[
partithura-estagiarios/frontend-intranet-elyte pull request #67
Opened 2023-11-13 13:53 UTC by oGalhardo

Arrumando bugs em geral no sistema de ramais, adicionando componentização para o form de raml e evitando a quebra de linha quando o usuário vai criar um sistema junto com ajustes nas traduções

2023-11-13 13:54 UTC, oGalhardo commented
Realizando correções abrangentes no sistema de extensões telefônicas, implementando uma abordagem de componentização para o formulário associado às configurações das extensões, e prevenindo a ocorrência de quebras de linha indesejadas durante a criação de um novo sistema. Ademais, efetuando refinamentos nos elementos tradutórios para assegurar uma experiência coesa e refinada ao usuário.

2023-11-14 11:03 UTC, whoistaiza commented on src/components/DynamicDialog/SystemModals/FormSystemDialog.vue
> +  console.log(enableConfirmation.value);
remover console.log

2023-11-14 11:04 UTC, whoistaiza commented on src/components/DynamicDialog/SystemModals/FormSystemDialog.vue
> +const activeConfirm = computed(() => {
Como o activeConfirm é uma computed que retorna o valor de enableConfirmation apenas para habilitar e desabilitar o botão, porque não colocar o enableConfirmation no disabled do botão?

2023-11-14 11:07 UTC, whoistaiza commented on src/components/Ramais/Ramais.vue
> +const emits = defineEmits(["reload", "cancel"]);
não precisa definir os eventos se tu não ta emitindo os eventos. no @reload e @cancel você está recebendo eles apenas

2023-11-14 11:08 UTC, whoistaiza commented on src/components/Ramais/modais/AddRamal.vue
> +    default: {},
default de objeto não é () => ({}) ?

2023-11-14 11:08 UTC, whoistaiza commented on src/components/Ramais/modais/AddRamal.vue
> +async function addRamal(form: Object) {
Se tu tem o tipo que a mutation AddRamal recebe, poderia usar aqui

2023-11-14 11:09 UTC, whoistaiza commented on src/components/Ramais/modais/AddRamal.vue
> +  console.log();
remover log

2023-11-14 11:11 UTC, whoistaiza commented on src/components/Ramais/modais/AddRamal.vue
> +  if (result !== undefined) {
qualquer coisa diferente de undefined significa que deu certo?

2023-11-14 11:11 UTC, whoistaiza commented on src/components/Ramais/modais/AddRamal.vue
> +      :isActive="true"
is-active

2023-11-14 11:12 UTC, whoistaiza commented on src/components/Ramais/modais/AddRamal.vue
> +      @some-form="(form) => addRamal(form)"
@some-form="addRamal" não funciona?

2023-11-14 11:13 UTC, whoistaiza commented on src/components/Ramais/modais/EditRamal.vue
> +      :isActive="true"
somente is-active deve funcionar

2023-11-14 11:13 UTC, taizamoura commented on src/components/Ramais/modais/EditRamal.vue
> +      @some-form="(form) => updateRamal(form)"
@some-form="updateRamal" deve funcionar

2023-11-14 11:14 UTC, whoistaiza commented on src/components/Ramais/modais/FormRamal.vue
> +      :disabled="!activeConfirm"
por que não usar o enableConfirmation direto aqui?

2023-11-14 11:16 UTC, whoistaiza commented on src/components/TabHeader.vue
>  <template>
template não deveria estão primeiro que a tag script?

2023-11-14 11:21 UTC, whoistaiza approved these changes

2023-11-14 11:50 UTC, oGalhardo commented on src/components/Ramais/modais/AddRamal.vue
> +  if (result !== undefined) {
isso

2023-11-14 11:50 UTC, oGalhardo commented on src/components/Ramais/modais/AddRamal.vue
> +      @some-form="(form) => addRamal(form)"
Funcionou

2023-11-14 11:52 UTC, oGalhardo commented on src/components/Ramais/modais/EditRamal.vue
> +      @some-form="(form) => updateRamal(form)"
Funcinou

2023-11-14 11:53 UTC, oGalhardo commented on src/components/TabHeader.vue
>  <template>
A príncipio não me passaram nenhum padrão

2023-11-14 12:00 UTC, taizamoura commented on src/components/Ramais/modais/AddRamal.vue
> +    <FormRamal :is-active="true" :item="item" @some-form="addRamal" />
só is-active funciona, quando tu quer o mandar o valor 'true' pra uma prop, só de colocar ela já se tem o mesmo comportamento: 
 <FormRamal is-active :item="item" @some-form="addRamal" />

2023-11-14 12:00 UTC, taizamoura commented on src/components/Ramais/modais/EditRamal.vue
> +    <FormRamal :is-active="true" :item="form" @some-form="updateRamal" />
mesma coisa aqui:
 <FormRamal :is-active="true" :item="item" @some-form="updateRamal" />

2023-11-14 12:12 UTC, whoistaiza approved these changes

2023-11-14 13:08 UTC, Sckyz requested changes

2023-11-14 13:08 UTC, Sckyz commented on locales/en/label.ts
>    sector: "Sector",
Department é melhor que sector

2023-11-14 13:08 UTC, Sckyz commented on locales/en/label.ts
> +  sectorUser: "Name of Sector",
como assim sector user é nome do setor?

2023-11-14 13:08 UTC, Sckyz commented on locales/en/label.ts
> +  ramalUser: "Sector Member ",
novamente, como que ramal user é membro do setor?

2023-11-14 13:08 UTC, Sckyz commented on locales/en/label.ts
> +  sublabel: "description",
se é description , pq a chave é sublabel?

2023-11-14 13:08 UTC, Sckyz commented on src/components/Ramais/modais/FormRamal.vue
> +      label="Confirmar"
tradução

2023-11-14 13:08 UTC, Sckyz commented on src/components/TabHeader.vue
>  <template>
a principio o padrao é script primeiro, é o que eu e a Laura usamos

2023-11-23 13:43 UTC, merged